name: Build and deploy Python Function App - GestorTarefasFunctionApp202203

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  FUNCTION_FOLDER: 'function'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup do Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.FUNCTION_FOLDER }}/requirements.txt

      - name: Criar ficheiro ZIP apenas da pasta da Function
        run: |
          cd ${{ env.FUNCTION_FOLDER }}
          zip -r ../function.zip .

      - name: Fazer upload do artefacto
        uses: actions/upload-artifact@v4
        with:
          name: function-zip
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fazer download do artefacto
        uses: actions/download-artifact@v4
        with:
          name: function-zip

      - name: Descomprimir para verificação (opcional)
        run: unzip -l function.zip

      - name: Publicar na Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'GestorTarefasFunctionApp202203'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f44bec2ac88e4dc4a7f47a2b257ef725 }}
          package: function.zip
